version: 2
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    steps:
      - checkout
      - run:
          name: installing Dependencies
          command: |
            apt-get update
            apt-get install wget -y
            apt-get install tidy -y 
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64
            chmod +x hadolint
            mv hadolint /bin/hadolint

      # run lint!
      - run:
          name: run lint
          command: |
